name: flibusta
description: Unofficial mobile application for site https://flibusta.is

version: 0.7.1+42

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  utopic_tor_onion_proxy: ^0.3.1

  flutter_typeahead: ^3.1.3
  mask_text_input_formatter: ^1.2.1

  shared_preferences: ^2.0.5
  flutter_local_notifications: ^5.0.0+4
  utopic_toast: ^1.0.0

  url_launcher: ^6.0.3

  font_awesome_flutter: ^9.0.0
  eva_icons_flutter: ^3.0.0

  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  rxdart: ^0.27.0
  equatable: ^2.0.0
  provider: ^5.0.0

  path_provider: ^2.0.1
  utopic_open_file: ^2.0.0

  html: ^0.15.0
  permission_handler: ^6.1.3
  
  flutter_slidable: ^0.6.0
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  launch_review: ^3.0.1
  package_info: ^2.0.0
  flare_flutter: ^3.0.0
  
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4

  share: ^2.0.1
  
  flutter_svg: ^0.22.0
  
  json_annotation: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/Logo.png
    - assets/img/utopic_narwhal.png
    - assets/img/4pda_logo.svg
    - assets/img/tor_logo.svg
    - assets/img/onion_services.svg
    - assets/animations/like.flr
    - assets/animations/empty_state.flr
    - assets/animations/books_placeholder.flr
    - assets/animations/long_tap.flr

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
